/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as ApiExtractPresetRouteImport } from './routes/api/extract-preset'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiGenerateVideoRouteImport } from './routes/api/generate-video'
import { Route as ApiVideoStatusRouteImport } from './routes/api/video-status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractPresetRoute = ApiExtractPresetRouteImport.update({
  id: '/api/extract-preset',
  path: '/api/extract-preset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVideoRoute = ApiGenerateVideoRouteImport.update({
  id: '/api/generate-video',
  path: '/api/generate-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoStatusRoute = ApiVideoStatusRouteImport.update({
  id: '/api/video-status',
  path: '/api/video-status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/api/extract-preset': typeof ApiExtractPresetRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/video-status': typeof ApiVideoStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/api/extract-preset': typeof ApiExtractPresetRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/video-status': typeof ApiVideoStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/api/extract-preset': typeof ApiExtractPresetRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/video-status': typeof ApiVideoStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/embed'
    | '/api/extract-preset'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/video-status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/embed'
    | '/api/extract-preset'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/video-status'
  id:
    | '__root__'
    | '/'
    | '/embed'
    | '/api/extract-preset'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/video-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedRoute: typeof EmbedRoute
  ApiExtractPresetRoute: typeof ApiExtractPresetRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGenerateVideoRoute: typeof ApiGenerateVideoRoute
  ApiVideoStatusRoute: typeof ApiVideoStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-preset': {
      id: '/api/extract-preset'
      path: '/api/extract-preset'
      fullPath: '/api/extract-preset'
      preLoaderRoute: typeof ApiExtractPresetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-video': {
      id: '/api/generate-video'
      path: '/api/generate-video'
      fullPath: '/api/generate-video'
      preLoaderRoute: typeof ApiGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-status': {
      id: '/api/video-status'
      path: '/api/video-status'
      fullPath: '/api/video-status'
      preLoaderRoute: typeof ApiVideoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedRoute: EmbedRoute,
  ApiExtractPresetRoute: ApiExtractPresetRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGenerateVideoRoute: ApiGenerateVideoRoute,
  ApiVideoStatusRoute: ApiVideoStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
